version: '2'
services:
  app:
    image: youlovesaturn/rsstgbot
    restart: always
    environment:
      TOKEN: "<TELEGRAM BOT TOKEN>"
      CHANNEL: "<ID OF THE CHANNEL TO POST TO>"
      FEEDURL: "<RSS URL>"
      DISABLE_PREVIEW: "<TRUE OR FALSE>"
    volumes: 
        - data:/data

volumes:
    data: