version: '2'
services:
  app:
    image: ghcr.io/youlovesaturn/rsstgbot
    restart: always
    container_name: rsstgbot
    environment:
      TOKEN: "<TELEGRAM BOT TOKEN>"
      CHANNEL: "<ID OF THE CHANNEL TO POST TO>"
      FEEDURL: "<RSS URL>"
      DISABLE_PREVIEW: "<TRUE OR FALSE>"
      FILENAME: "<DATA/LASTDATE>"
    volumes: 
        - data:/data

volumes:
    data: